'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='shangan-dazi-v1';
const DAILY_GOAL=10;
const CAT=['常识判断','言语理解','判断推理','数量关系','资料分析','政治理论'];
const SYMBOL=['✦','Aa','◈','∑','▥','★'];
const DESCR=['先来一点新考点','读懂题意，选对词语','给思路做个热身','数字也能变得亲切','找准分母，再算一遍','积累概念，稳住基础'];
const TITLES={learn:'学习地图',wrong:'错题复仇',stats:'我的成长',sources:'题库与资料'};
let storageOK=true;
function validPending(p){return p&&Array.isArray(p.ids)&&p.ids.length&&p.ids.every(id=>BANK.some(q=>q.id===id))&&Number.isInteger(p.index)&&p.index>=0&&p.index<=p.ids.length&&Number.isInteger(p.right)&&p.right>=0&&p.right<=p.index&&Number.isFinite(p.xp)&&p.xp>=0&&typeof p.title==='string'&&(p.cat===null||CAT.includes(p.cat));}
let state={xp:0,days:{},wrong:[],correct:[],attempted:[],completed:[],reminder:{mode:'off',minutes:15,quiet:true}};
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&typeof saved==='object'){if(Number.isFinite(saved.xp)&&saved.xp>=0)state.xp=saved.xp;for(const k of ['wrong','correct','attempted'])if(Array.isArray(saved[k]))state[k]=saved[k].filter(id=>BANK.some(q=>q.id===id));if(Array.isArray(saved.completed))state.completed=saved.completed.filter(c=>CAT.includes(c));if(saved.days&&typeof saved.days==='object'&&!Array.isArray(saved.days))for(const [d,ids] of Object.entries(saved.days))if(/^\d{4}-\d{2}-\d{2}$/.test(d)&&Array.isArray(ids))state.days[d]=ids.filter(id=>BANK.some(q=>q.id===id));if(validPending(saved.pending))state.pending=saved.pending;if(saved.reminder&&['off','gentle','strict','drama'].includes(saved.reminder.mode))state.reminder={mode:saved.reminder.mode,minutes:[5,15,30].includes(saved.reminder.minutes)?saved.reminder.minutes:15,quiet:saved.reminder.quiet!==false};}}catch{storageOK=false;}
function dateKey(d=new Date()){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d);const v=t=>p.find(x=>x.type===t).value;return `${v('year')}-${v('month')}-${v('day')}`;}
function dayAgo(n){return dateKey(new Date(Date.now()-n*86400000));}
function dailyCount(){return (state.days[dateKey()]||[]).length;}
function streak(){let n=0;let i=(state.days[dayAgo(0)]||[]).length?0:1;while((state.days[dayAgo(i)]||[]).length){n++;i++;}return n;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;toast('浏览器暂时无法保存记录，本次仍可以正常练习。');}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
let toastTimer;
function toast(s){$('#toast').textContent=s;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('#toast').hidden=true;},6500);}
let view='learn',session=null,lastFocus=null,reminderTimer=null;
function showView(next){if(!TITLES[next])return;view=next;$$('.view').forEach(e=>e.hidden=e.id!==next);$$('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view===next));$('#viewTitle').textContent=TITLES[next];render();window.scrollTo({top:0,behavior:'smooth'});}
function render(){const n=dailyCount();$('#resumeCard').hidden=!state.pending;$('#resumeCard').innerHTML=state.pending?`<div><h3>上次的努力，接着走。</h3><p>${esc(state.pending.title)} · 已完成 ${state.pending.index}/${state.pending.ids.length} 题</p></div><button class="primary" data-action="resume">继续练习</button>`:'';$('#xp').textContent=state.xp;$('#streak').textContent=streak();$('#wrongBadge').textContent=state.wrong.length;$('#dailyCount').textContent=`${Math.min(n,DAILY_GOAL)} / ${DAILY_GOAL}`;$('#dailyInline').textContent=`${Math.min(n,DAILY_GOAL)} / ${DAILY_GOAL}`;$('#dailyProgress').style.width=`${Math.min(n/DAILY_GOAL,1)*100}%`;$('#dailyText').textContent=n>=DAILY_GOAL?'yaya你最棒！今天的小目标拿下啦。':'yaya，完成 10 道题，给今天一个小成就。';$('#dailyStart').textContent=n>=DAILY_GOAL?'再练 10 题':'开始今日 10 题';$('#buddyMessage').innerHTML=n>=DAILY_GOAL?'yaya你最棒，今天值得一颗星！<br>休息一下，明天小岸继续陪你。':'yaya加油！我都到自习室了。<br>就差你和今天的 10 道题！';const first=CAT.find(c=>!state.completed.includes(c));$('#path').innerHTML=CAT.map((c,i)=>{const done=state.completed.includes(c),current=c===first;return `<div class="level"><button class="levelbutton ${done?'done':current?'current':''}" data-cat="${c}" aria-label="${c}，5道题，${done?'已完成，可重练':'开始练习'}"><span>${done?'✓':SYMBOL[i]}</span><small>${String(i+1).padStart(2,'0')}</small></button><div class="leveltext">${current?'<span class="startpill">从这里开始</span>':''}<h3>${c}</h3><p>${done?'已完成 · 再巩固一次':DESCR[i]}</p></div></div>`;}).join('');if(view==='wrong')renderWrong();if(view==='stats')renderStats();if(view==='sources')renderSources();}
function renderWrong(){const list=BANK.filter(q=>state.wrong.includes(q.id));$('#wrong').innerHTML=`<div class="pageheader"><div class="eyebrow">COME BACK STRONGER</div><h1>错题，是下一次的得分点。</h1><p>答对就移出错题本。慢慢来，把它们一个个拿下。</p></div>`+(list.length?`<div class="wrongtools"><button class="primary" data-action="wrongAll">开始错题复仇</button><span>${list.length} 道待攻克</span></div>`+list.map(q=>`<article class="wrongitem"><small>${esc(q.cat)} · ${esc(q.tag)}</small><h3>${esc(q.q)}</h3><button class="textbtn" data-retry="${q.id}">重做这道题</button></article>`).join(''):`<div class="empty"><span>✨</span><h2>这里还是一片清爽</h2><p>答错的题会自动收进来。先去试一关吧。</p><button class="primary" data-action="backLearn">去学习地图</button></div>`);}
function renderStats(){const accuracy=state.attempted.length?Math.round(state.correct.length/state.attempted.length*100):0;$('#stats').innerHTML=`<div class="pageheader"><div class="eyebrow">SMALL STEPS, REAL PROGRESS</div><h1>yaya，每一点进步都算数。</h1><p>yaya你最棒！今天的努力，正在变成明天的底气。</p></div><div class="growthgrid"><section class="card"><h3>累计经验</h3><b>${state.xp} XP</b><small>首次答对 +10，首次答错 +2</small></section><section class="card"><h3>连续学习</h3><b>${streak()} 天</b><small>每天做 1 道题，就算打卡</small></section><section class="card"><h3>已掌握题目</h3><b>${state.correct.length} / ${BANK.length}</b><small>练过的题中，${accuracy}% 已答对过</small></section></div><section class="card" style="margin-top:22px"><h3>最近 7 天的小脚印</h3><div class="week">${[6,5,4,3,2,1,0].map(n=>{const d=dayAgo(n),count=(state.days[d]||[]).length;return `<div class="day"><span>${n===0?'今天':d.slice(5).replace('-','/')}</span><i class="${count?'done':''}">${count?'✓':'·'}</i><span>${count?count+'题':'未练习'}</span></div>`;}).join('')}</div></section><section class="card" style="margin-top:22px"><h3>我的小里程碑</h3><p style="margin-top:16px;color:#7d8882">${state.completed.length===6?'🏆 六个模块都练过了！':state.completed.length?'✧ 已完成 '+state.completed.length+' 个模块，继续一步一步走。':'🌱 完成第一关，点亮你的第一个里程碑。'}</p></section><p class="localnote">${storageOK?'记录仅保存在当前浏览器；换设备、清除浏览器数据后不会同步。':'当前浏览器无法保存记录；本次学习仍可进行，关闭后可能丢失。'} · 学习日按北京时间计算。</p>`;}
function renderSources(){const adapted=BANK.filter(q=>q.tag.includes('改编')).length;$('#sources').innerHTML=`<div class="pageheader"><div class="eyebrow">KNOW WHAT YOU ARE PRACTICING</div><h1>题有出处，练得明白。</h1><p>国考在沈阳参加，行测按全国考试内容练习。</p></div><div class="sourcecount"><span>${BANK.length} 道站内练习</span><span>${adapted} 道考点改编</span><span>${BANK.length-adapted} 道原创练习</span></div><section class="sourcecard"><h3>短关卡，练最新与历年考点</h3><p>题干、数字和解析由本站重新编写，标明年份与来源。属于考点改编，回忆卷并非官方发布试卷。</p><div class="practice-buttons">${[2026,2025,2024].map(y=>`<button class="primary" data-year="${y}">${y} 考点练习</button>`).join('')}<button class="primary" data-action="material">一份材料 · 5 道题</button></div></section><section class="sourcecard"><h3>历年原卷资料</h3><p>已整理你提供仓库中的 2024—2026 年三类国考试卷入口，共 54 个模块链接。点击打开仓库原卷；完整原卷尚未导入本站练习。</p><div class="paper-filters"><label>年份<select id="paperYear">${[2026,2025,2024].map(y=>`<option>${y}</option>`).join('')}</select></label><label>试卷类别<select id="paperKind">${[...new Set(PAPERS.map(p=>p.kind))].map(k=>`<option>${esc(k)}</option>`).join('')}</select></label></div><div id="paperLinks"></div><a href="${SOURCES.repo.url}" target="_blank" rel="noopener noreferrer">打开 ERRRC/xingcezhenti 仓库</a></section><section class="sourcecard"><h3>练习范围与考试信息</h3><p>覆盖六个模块，新增数量运算、增长率、比重和材料综合题。当前题目以基础练习为主，尚未包含图形推理和申论训练。报名安排与职位分类以最新官方公告为准。</p><a href="${SOURCES.outline.url}" target="_blank" rel="noopener noreferrer">2026年度官方公共科目大纲</a><br><a href="https://www.scs.gov.cn/" target="_blank" rel="noopener noreferrer">国家公务员局官网</a></section>`;renderPaperLinks();}
function renderPaperLinks(){const y=Number($('#paperYear').value),k=$('#paperKind').value;$('#paperLinks').innerHTML=PAPERS.filter(p=>p.year===y&&p.kind===k).map(p=>`<a class="paper-link" href="${p.url}" target="_blank" rel="noopener noreferrer"><span>${esc(p.cat)}</span><small>${p.count} 道原卷题 ↗</small></a>`).join('');}
function prioritize(list){const used=state.days[dateKey()]||[];return [...list].sort((a,b)=>Number(used.includes(a.id))-Number(used.includes(b.id))||Number(state.attempted.includes(a.id))-Number(state.attempted.includes(b.id))||a.id-b.id);}
function moduleSet(cat){return prioritize(BANK.filter(q=>q.cat===cat)).slice(0,5);}
function dailySet(){const used=state.days[dateKey()]||[],out=[];const push=q=>{if(q&&!out.some(x=>x.id===q.id))out.push(q);};prioritize(BANK.filter(q=>state.wrong.includes(q.id)&&!used.includes(q.id))).slice(0,3).forEach(push);const queues=CAT.map(c=>prioritize(BANK.filter(q=>q.cat===c&&!used.includes(q.id))));while(out.length<DAILY_GOAL&&queues.some(q=>q.length)){for(const queue of queues){while(queue.length&&out.some(q=>q.id===queue[0].id))queue.shift();if(out.length<DAILY_GOAL)push(queue.shift());}}for(const q of prioritize(BANK)){if(out.length>=DAILY_GOAL)break;push(q);}return out;}
function checkpoint(next=session.index){state.pending={ids:session.questions.map(q=>q.id),title:session.title,cat:session.cat,index:next,right:session.right,xp:session.xp};save();}
function resumeQuiz(){const p=state.pending;if(!validPending(p))return;openQuiz(p.ids.map(id=>BANK.find(q=>q.id===id)),p.title,p.cat,p);}
function openQuiz(questions,title,cat=null,pending=null){if(!questions.length){toast('已经没有待复习的错题啦！');return;}lastFocus=document.activeElement;session={questions,title,cat,index:0,selected:null,checked:false,right:0,xp:0,finished:false};if(pending)Object.assign(session,{index:pending.index,right:pending.right,xp:pending.xp});checkpoint();$('#quiz').showModal();if(session.index===questions.length)finishSession();else drawQuestion();render();}
function drawQuestion(){const q=session.questions[session.index];$('#quizProgress').style.width=`${session.index/session.questions.length*100}%`;$('#quizCounter').textContent=`${session.index+1} / ${session.questions.length}`;$('#quizBody').innerHTML=`<div class="qmeta"><span>${esc(session.title)}</span><span class="${q.tag.includes('2026')?'latest':''}">${esc(q.tag)}</span></div>${q.material?`<details class="material" open><summary>阅读材料 · 原创数据</summary><div>${q.material}</div></details>`:''}<h2 class="question">${esc(q.q)}</h2><div class="options">${q.options.map((o,i)=>`<button class="option" data-answer="${i}" aria-label="${'ABCD'[i]}，${esc(o)}"><span class="letter">${'ABCD'[i]}</span><span>${esc(o)}</span></button>`).join('')}</div>`;$('#feedback').innerHTML='';$('#check').textContent='检查答案';$('#check').disabled=true;$('#quizTip').textContent='选出最恰当的一项';$('#quiz').scrollTop=0;$('#quizBody .option')?.focus({preventScroll:true});}
function selectOption(i){if(!session||session.checked||session.finished||!Number.isInteger(i)||i<0||i>3)return false;session.selected=i;$$('.option').forEach((e,n)=>{e.classList.toggle('selected',n===i);e.setAttribute('aria-pressed',String(n===i));});$('#check').disabled=false;return true;}
function checkAnswer(){if(!session||session.finished||session.selected===null)return false;const q=session.questions[session.index];if(session.checked){session.index++;session.selected=null;session.checked=false;if(session.index>=session.questions.length)finishSession();else drawQuestion();return true;}session.checked=true;const right=session.selected===q.answer;session.right+=right?1:0;const firstAttempt=!state.attempted.includes(q.id),firstCorrect=right&&!state.correct.includes(q.id);let gained=firstCorrect?10:firstAttempt?2:0;state.xp+=gained;session.xp+=gained;if(firstAttempt)state.attempted.push(q.id);if(firstCorrect)state.correct.push(q.id);if(right)state.wrong=state.wrong.filter(id=>id!==q.id);else if(!state.wrong.includes(q.id))state.wrong.push(q.id);const day=dateKey();if(!state.days[day])state.days[day]=[];if(!state.days[day].includes(q.id))state.days[day].push(q.id);checkpoint(session.index+1);render();$$('.option').forEach((e,n)=>{e.disabled=true;e.classList.toggle('correct',n===q.answer);e.classList.toggle('incorrect',!right&&n===session.selected);});$('#feedback').innerHTML=`<div class="feedback ${right?'':'bad'}"><h3>${right?'yaya你最棒，答对啦！':'yaya别灰心，这道下次一定拿下。'} ${gained?'+'+gained+' XP':''}</h3><p>${right?'':'正确答案：'+ 'ABCD'[q.answer]+'。 '}${esc(q.explain)}</p><a href="${q.sourceURL||SOURCES[q.source].url}" target="_blank" rel="noopener noreferrer">${q.source==='outline'?'题型参考：':'考点来源：'}${esc(SOURCES[q.source].name)}${q.qid?` · 原题编号 ${q.qid}`:''}</a></div>`;$('#quizProgress').style.width=`${(session.index+1)/session.questions.length*100}%`;$('#quizTip').textContent=right?'小岸：yaya加油，这一步走得很稳！':'小岸：yaya，错题已收好，下次拿下它。';$('#check').textContent=session.index===session.questions.length-1?'查看本关成绩':'继续';$('#check').focus({preventScroll:true});return true;}
function finishSession(){session.finished=true;delete state.pending;if(session.cat&&!state.completed.includes(session.cat))state.completed.push(session.cat);save();render();$('#quizCounter').textContent='完成';$('#quizProgress').style.width='100%';$('#quizBody').innerHTML=`<div class="summary"><div class="summary-emoji">${session.right===session.questions.length?'🏆':'🌟'}</div><h2>yaya，又离上岸近了一点！</h2><p>${session.right===session.questions.length?'yaya你最棒，全对！小岸给你鼓掌！':'yaya加油，愿意再试一次就已经很棒。'}</p><div class="summarynums"><div><b>${session.right}/${session.questions.length}</b><small>答对题数</small></div><div><b>+${session.xp}</b><small>本关经验</small></div></div><p>${dailyCount()>=DAILY_GOAL?'今日10题目标已达成 ✓':'今日已练 '+dailyCount()+' 道，继续积累。'}</p></div>`;$('#feedback').innerHTML='';$('#quizTip').textContent='把这份小成就带回去';$('#check').textContent='回到学习';$('#check').disabled=false;$('#check').focus();}
function closeQuiz(){if($('#quiz').open)$('#quiz').close();if(session&&!session.finished)toast('进度已保存，回来点击“继续练习”就好。');session=null;render();if(lastFocus?.isConnected)lastFocus.focus();}
function openReminder(){lastFocus=document.activeElement;$('#reminderMode').value=state.reminder.mode;$('#reminderMinutes').value=state.reminder.minutes;$('#quiet').checked=state.reminder.quiet;$('#reminderDialog').showModal();}
const REMINDERS={gentle:['yaya加油！今天再进步一点点，小岸陪你做10题。','yaya你最棒！喝口水，伸个懒腰，再拿下一道题吧。'],strict:['yaya，自习室已就位。先刷10题，再放心休息。','yaya加油，收收心！今天的10题等你来拿下。'],drama:['yaya你最棒，但你人呢？小岸已经等到想嘎了。','yaya加油！题目都快在自习室长蘑菇了，快来救救它。','yaya，再不来小岸就要替你考公了。可是鸭鸭不会涂答题卡啊！']};
function previewReminder(){const mode=$('#reminderMode').value;const arr=REMINDERS[mode]||REMINDERS.drama;toast('🦆 小岸：'+arr[Math.floor(Math.random()*arr.length)]);}
function startReminder(){clearInterval(reminderTimer);if(state.reminder.mode==='off')return;reminderTimer=setInterval(()=>{const hour=Number(new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Shanghai',hour:'numeric',hourCycle:'h23'}).format(new Date()));if(dailyCount()>=DAILY_GOAL||$('#quiz').open||$('#reminderDialog').open||document.hidden||state.reminder.quiet&&(hour>=22||hour<8))return;const arr=REMINDERS[state.reminder.mode];toast('🦆 小岸：'+arr[Math.floor(Math.random()*arr.length)]);},state.reminder.minutes*60000);}
$$('[data-view]').forEach(e=>e.addEventListener('click',()=>showView(e.dataset.view)));$('.brand').addEventListener('click',e=>{e.preventDefault();showView('learn');});$('#path').addEventListener('click',e=>{const btn=e.target.closest('[data-cat]');if(btn)openQuiz(moduleSet(btn.dataset.cat),btn.dataset.cat,btn.dataset.cat);});$('#dailyStart').addEventListener('click',()=>state.pending?.title==='每日 10 题'?resumeQuiz():openQuiz(dailySet(),'每日 10 题'));$('#quizBody').addEventListener('click',e=>{const btn=e.target.closest('[data-answer]');if(btn)selectOption(Number(btn.dataset.answer));});$('#check').addEventListener('click',()=>{if(session?.finished)closeQuiz();else checkAnswer();});$('#quizClose').addEventListener('click',closeQuiz);$('#quiz').addEventListener('cancel',e=>{e.preventDefault();closeQuiz();});for(const id of ['remindTop','remindOpen'])$('#'+id).addEventListener('click',openReminder);$('#reminderClose').addEventListener('click',()=>$('#reminderDialog').close());$('#saveReminder').addEventListener('click',()=>{state.reminder={mode:$('#reminderMode').value,minutes:Number($('#reminderMinutes').value),quiet:$('#quiet').checked};save();startReminder();$('#reminderDialog').close();toast(state.reminder.mode==='off'?'好，小岸先安静陪你。':'已设置。网页打开时，小岸会按你的节奏提醒。');});$('#testReminder').addEventListener('click',previewReminder);
document.addEventListener('click',e=>{const btn=e.target.closest('[data-action],[data-retry],[data-year]');if(!btn)return;if(btn.dataset.year){const year=Number(btn.dataset.year);openQuiz(prioritize(BANK.filter(q=>q.year===year||year===2026&&q.tag==='2026考点改编')).slice(0,5),year+' 考点练习');return;}if(btn.dataset.action==='resume')resumeQuiz();if(btn.dataset.action==='material')openQuiz(BANK.filter(q=>q.material),'材料综合练习');if(btn.dataset.retry){openQuiz(BANK.filter(q=>q.id===Number(btn.dataset.retry)),'错题复仇');return;}if(btn.dataset.action==='wrongAll')openQuiz(BANK.filter(q=>state.wrong.includes(q.id)),'错题复仇');if(btn.dataset.action==='backLearn')showView('learn');if(btn.dataset.action==='latest')openQuiz(BANK.filter(q=>q.tag==='2026考点改编'),'2026 考点热身');});
document.addEventListener('keydown',e=>{if(!$('#quiz').open||!session||session.checked||session.finished)return;const i='1234'.indexOf(e.key);if(i>=0){e.preventDefault();selectOption(i);}});
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'start_practice',title:'开始国考练习',description:'打开指定行测模块的5题练习，不提交答案。',inputSchema:{type:'object',properties:{category:{type:'string',enum:CAT}},required:['category'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!CAT.includes(input.category))throw new Error('模块不存在');if($('#quiz').open||$('#reminderDialog').open)throw new Error('请先结束当前练习或关闭设置');openQuiz(moduleSet(input.category),input.category,input.category);return {category:input.category,count:session.questions.length,currentQuestion:session.questions[0].q};}});}catch{}}
document.addEventListener('change',e=>{if(['paperYear','paperKind'].includes(e.target.id))renderPaperLinks();});
render();startReminder();
