'use strict';
const WALLET_KEY='yaya-wishes-v1';
let wallet={points:0,challenges:{},orders:[],ledger:[]};
const GIFTS=[['coffee','☕','奶茶自由券',200,'给努力的自己加一点甜'],['perfume','🧴','心动香水',1500,'把喜欢的香气带回家'],['bag','👜','出门快乐包包',4500,'装下生活，也装下好心情'],['hotel','🛎️','豪华酒店度假',6000,'认真休息，也是一种奖励'],['camera','📷','记录生活的相机',8000,'记录每一个值得记住的瞬间'],['xinjiang','🏔️','新疆机酒报销',15000,'去看看远方的风和雪山']];
function initWallet(){try{const v=JSON.parse(localStorage.getItem(WALLET_KEY)||'null');if(v&&Number.isSafeInteger(v.points)&&v.points>=0&&v.challenges&&Array.isArray(v.orders)&&Array.isArray(v.ledger))wallet=v;}catch{} }
function saveWallet(){try{localStorage.setItem(WALLET_KEY,JSON.stringify(wallet));}catch{toast('积分暂时无法保存，请勿关闭页面，并及时备份。');}}
function challenge(day=dateKey()){if(!wallet.challenges[day]){let seed=[...day].reduce((a,c)=>a*31+c.charCodeAt(0),0)>>>0;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const queues=CAT.map(c=>BANK.filter(q=>q.cat===c).map(q=>({q,r:rand()})).sort((a,b)=>a.r-b.r).map(x=>x.q));const ids=[];for(let i=0;ids.length<20;i++)for(const list of queues)if(list[i]&&ids.length<20)ids.push(list[i].id);wallet.challenges[day]={ids,answers:{},complete:false,perfect:false};saveWallet();}return wallet.challenges[day];}
function credit(n,label){wallet.points+=n;wallet.ledger.push({date:dateKey(),n,label});}
function awardDaily(day,id,right){const d=challenge(day);if(!d.ids.includes(id)||Object.hasOwn(d.answers,id))return 0;d.answers[id]=!!right;let n=right?5:2;credit(n,right?'每日答对':'每日作答');if(Object.keys(d.answers).length===20&&!d.complete){d.complete=true;credit(20,'每日20题完成');n+=20;if(Object.values(d.answers).every(Boolean)){d.perfect=true;credit(50,'首次全对奖励');n+=50;toast('🏆 yaya你最棒！20题全对，额外奖励已到账！');}}saveWallet();return n;}
function redeem(id){const gift=GIFTS.find(g=>g[0]===id);if(!gift||wallet.points<gift[3])return false;wallet.points-=gift[3];wallet.orders.push({id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),gift:id,cost:gift[3],date:dateKey(),status:'pending'});wallet.ledger.push({date:dateKey(),n:-gift[3],label:gift[2]+'兑换申请'});saveWallet();return true;}
function cancelOrder(id){const o=wallet.orders.find(o=>o.id===id);if(!o||o.status!=='pending')return false;o.status='cancelled';credit(o.cost,'撤销兑换返还');saveWallet();return true;}
function renderGifts(){const next=GIFTS.find(g=>g[3]>wallet.points);$('#gifts').innerHTML=`<div class="pageheader"><div class="eyebrow">EFFORT BECOMES SOMETHING LOVELY</div><h1>yaya的心愿商店</h1><p>每一次认真，都在靠近一个喜欢的礼物。</p></div><section class="wallet-card"><div><small>我的可用积分</small><h2>💎 ${wallet.points.toLocaleString()}</h2><p>${next?'距离「'+next[2]+'」还差 '+(next[3]-wallet.points)+' 积分':'心愿都触手可及啦，yaya你最棒！'}</p></div><span>✦</span></section><div class="gift-grid">${GIFTS.map(g=>`<article class="gift-card"><div class="gift-art">${g[1]}</div><small>FOR YAYA · 心愿 ${String(GIFTS.indexOf(g)+1).padStart(2,'0')}</small><h3>${g[2]}</h3><p>${g[4]}</p><div class="gift-bottom"><b>💎 ${g[3]}</b><button class="primary" data-gift="${g[0]}" ${wallet.points<g[3]?'disabled':''}>${wallet.points<g[3]?'继续攒分':'申请兑换'}</button></div></article>`).join('')}</div><section class="sourcecard"><h3>积分怎么攒？</h3><p>每日固定20题，首次答对 +5，答错也有 +2；完成20题额外 +20；20题首次作答全部正确再 +50。完美一天共170分！每日按北京时间更新，中途退出可以继续。专项练习攒经验，重复答题不重复领积分。</p><p>礼物是你们之间的心愿约定，具体款式、金额和出行安排由你们确认。申请兑换会扣积分，复制申请发给搭子后人工兑现；尚未兑现的申请可以撤销返还。已兑现的申请请勿撤销。</p></section><section class="sourcecard"><h3>我的兑换申请</h3>${wallet.orders.length?wallet.orders.slice().reverse().map(o=>`<div class="order"><div><b>${GIFTS.find(g=>g[0]===o.gift)?.[2]||'礼物'}</b><p>${esc(o.date)} · ${o.cost} 分 · ${o.status==='cancelled'?'已撤销':'待搭子确认'}<br>申请号 ${esc(o.id)}</p></div>${o.status==='pending'?`<div><button class="textbtn" data-copy-order="${esc(o.id)}">复制申请</button><button class="textbtn" data-cancel-order="${esc(o.id)}">撤销</button></div>`:''}</div>`).join(''):'<p>第一份礼物，在未来等你。</p>'}</section><section class="sourcecard"><h3>保管好你的努力</h3><p>积分和学习记录保存在当前浏览器，更换域名、设备或清除数据不会自动同步。下载备份可交给搭子留存。</p><button class="textbtn" data-export="yes">下载学习与积分备份 ↓</button><details><summary>最近积分记录</summary>${wallet.ledger.slice(-20).reverse().map(x=>`<p>${esc(x.date)} · ${esc(x.label)} <b>${x.n>0?'+':''}${x.n}</b></p>`).join('')}</details></section>`;}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-gift],[data-cancel-order],[data-copy-order],[data-export]');if(!b)return;if(b.dataset.gift){const g=GIFTS.find(g=>g[0]===b.dataset.gift);if(window.confirm(`用 ${g[3]} 积分申请「${g[2]}」？请和搭子确认礼物细节。`)){if(redeem(g[0]))toast('申请已创建！复制申请发给你的礼物搭子吧。');render();}}if(b.dataset.cancelOrder&&window.confirm('确认该申请尚未兑现，撤销并返还积分？')){cancelOrder(b.dataset.cancelOrder);render();}if(b.dataset.copyOrder){const o=wallet.orders.find(o=>o.id===b.dataset.copyOrder);const text=`yaya的礼物申请\n${GIFTS.find(g=>g[0]===o.gift)[2]} · ${o.cost}积分\n申请号：${o.id}\n日期：${o.date}\n款式、预算和安排一起确认。yaya加油！`;try{await navigator.clipboard.writeText(text);toast('申请已复制，发给搭子就好。');}catch{window.prompt('复制下面的兑换申请',text);}}if(b.dataset.export){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:1,date:dateKey(),learning:state,wallet},null,2)],{type:'application/json'}));a.download='yaya-study-backup-'+dateKey()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}});
