const fs=require('fs'),vm=require('vm'),assert=require('assert');
class El{constructor(){this.style={};this.dataset={};this.open=false;this.classList={toggle(){}};this.listeners={};this.isConnected=true;}addEventListener(n,f){this.listeners[n]=f}setAttribute(){}focus(){}showModal(){this.open=true}close(){this.open=false}set innerHTML(x){this.html=x}get innerHTML(){return this.html||''}}
const els=new Map(),get=s=>{if(!els.has(s))els.set(s,new El());return els.get(s)};let data={'shangan-dazi-v1':JSON.stringify({xp:52,wrong:[1],correct:[2],attempted:[1,2],days:{},completed:[]})};
const ctx=vm.createContext({document:{querySelector:get,querySelectorAll:s=>s==='.option'?[0,1,2,3].map(i=>get('o'+i)):[],addEventListener(){},activeElement:new El(),hidden:false},window:{scrollTo(){},confirm(){return true}},localStorage:{getItem:k=>data[k],setItem:(k,v)=>data[k]=v},Intl,Date,console,setTimeout(){},clearTimeout(){},setInterval(){},clearInterval(){}});
for(const f of ['questions.js','expanded.js','rewards.js','app.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);const run=s=>vm.runInContext(s,ctx);
assert.equal(run('BANK.length'),101);assert(run('BANK.every(q=>q.options.length===4&&q.answer>=0&&q.answer<4&&SOURCES[q.source])'));assert.equal(run('state.xp'),52);assert.equal(run('wallet.points'),0);assert.equal(run('new Set(dailySet().map(q=>q.id)).size'),20);assert.equal(run('new Set(dailySet().map(q=>q.cat)).size'),6);assert(run('JSON.stringify(dailySet())===JSON.stringify(dailySet())'));
run('startDaily();selectOption(session.questions[0].answer);checkAnswer();closeQuiz();resumeQuiz()');assert.equal(run('session.index'),1);assert.equal(run('wallet.points'),5);for(let i=1;i<20;i++)run('selectOption(session.questions[session.index].answer);checkAnswer();checkAnswer()');assert.equal(run('wallet.points'),170);assert.equal(run('dailyCount()'),20);assert(run('challenge().perfect'));assert.equal(run('awardDaily(dateKey(),challenge().ids[0],true)'),0);assert.equal(run('wallet.points'),170);
assert.equal(run("redeem('camera')"),false);run("credit(30,'test')");assert(run("redeem('coffee')"));assert.equal(run('wallet.points'),0);assert(run('cancelOrder(wallet.orders[0].id)'));assert.equal(run('wallet.points'),200);assert.equal(run('cancelOrder(wallet.orders[0].id)'),false);assert.equal(run('wallet.points'),200);
run("wallet.points=0;const d=challenge('2026-01-01');for(let i=0;i<20;i++)awardDaily('2026-01-01',d.ids[i],i!==0)");assert.equal(run('wallet.points'),117);assert.equal(run("awardDaily('2026-01-01',challenge('2026-01-01').ids[0],true)"),0);assert.equal(run("challenge('2026-01-01').perfect"),false);assert(run('BANK.filter(q=>q.source==="repo").every(q=>q.sourceURL&&q.qid)'));run("showView('gifts');showView('stats');showView('sources')");console.log('PASS: 101 questions, sources, daily20 stable/balanced, old-record migration, resume, perfect170 once, wrong117/no retry bonus, redemption debit/refund guards, page renders.');
